spring:
  application:
   name: processor
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
  mongodb:
    uri: ${MONGO_URL}

apps:
  collection: ${MONGO_COLLECTION}
  order-path: ${ORDER_PATH}
server:
  port: 8090
